name: Push lastest KernelSU
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        submodules: 'true'
        fetch-depth: 0
   
    - name: Update Repo
      id: version
      run: |
        git config --global user.name "H1mJT"
        git config --global user.email "himjyoti22@gmail.com"
        git submodule sync
        git submodule update --init --recursive
        cd $GITHUB_WORKSPACE/KernelSU
        git checkout main
        git pull
        cd .. && git add .
        git commit -m "Sync KernelSU to latest"
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
